### ISSUE TITLE
Typo in the docs regarding SystemEvents usage

### ISSUE THREAD

**Issue by oxysoft** [lazlo-bonin/gocs#1]
As I was quickly glancing over the main documentation, I noticed something odd where it is demoing `SystemEvents`. This is the line in question:

`collisionEvents[collidable.onEnter] = OnCollision(destructible, collision);`

I was wondering what kind of syntax this was and if there was something I didn't know about delegates in C#, but after looking at samples later on I realized this is most likely a typo, and this should be creating a separate delegate which forwards to OnCollision instead.

Note: the same typo can be found in 2-3 separate instances.

**Comment by lazlo-bonin** [comment]
Good catch, fixed, thanks!
